Style/RedundantReturn:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
